# Basic dependabot.yml file with
# minimum configuration for nuget
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/GreenEnergyHub.Conversion"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "NodaTime"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "nuget"
    directory: "/test/GreenEnergyHub.Conversion.Tests"
    schedule:
      interval: "weekly"
