# Basic dependabot.yml file with
# minimum configuration for nuget
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/ingestion/GreenEnergyHub.Ingestion.Synchronous/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/src/master-data/GreenEnergyHub.MasterData/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/src/master-data/GreenEnergyHub.Streaming/"
    schedule:
      interval: "daily"