# Basic dependabot.yml file with
# minimum configuration for nuget
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/GreenEnergyHub.Conversion"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/test/GreenEnergyHub.Conversion.Tests"
    schedule:
      interval: "weekly"
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
