name: 'Obtain Keyvault ID'
description: 'Obtains Key Vault Value. Note: expects Azure CLI to be installed on a runner.'
outputs:
  keyvault-id: 
    description: "Keyvault Id"
    value: ${{ steps.obtain-keyvault-id.outputs.keyvault-id }}
runs:
  using: "composite"
  steps:
    - id: obtain-keyvault-id
      run: |
        keyvault_id=$(az keyvault show -g ${{ env.RESOURCE_GROUP_NAME }} -n "energinetkv${{ env.ENV_NAME }}" | python -c "import sys, json; print(json.load(sys.stdin)['id'])")
        echo "::set-output name=keyvault-id::$keyvault_id"
      shell: bash
          