name: License Check CI

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  check-license-lines:
    name: Check License Lines
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check License Lines
      uses: kt3k/license_checker@v1.0.3