name: MarkdownCheck

on:
  push:
    branches: [ master ]
    paths:
    - '**.md'
  pull_request:
    branches: [ master ]
    paths:
    - '**.md'

jobs:
  # https://github.com/marketplace/actions/markdown-link-check
  md-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
  # https://github.com/marketplace/actions/github-spellcheck-action
  md-spell-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cp ${GITHUB_WORKSPACE}/.github/md-spell-check/spellcheck.yml ${GITHUB_WORKSPACE}/spellcheck.yml
    - run: cp ${GITHUB_WORKSPACE}/.github/md-spell-check/wordlist.txt ${GITHUB_WORKSPACE}/wordlist.txt
    - uses: rojopolis/spellcheck-github-actions@0.5.0
      name: Spellcheck
  # https://github.com/marketplace/actions/markdownlint-mdl-action
  md-lint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cp ${GITHUB_WORKSPACE}/.github/md-lint-check/.mdl.rb ${GITHUB_WORKSPACE}/.mdl.rb
    - run: cp ${GITHUB_WORKSPACE}/.github/md-lint-check/.mdlrc ${GITHUB_WORKSPACE}/.mdlrc
    - uses: actionshub/markdownlint@master
